server:
  port: 9999
  
  context-path: /uaa
  
logging:
  level:
    org.springframework.security: debug
    com.netflix.discovery: off

security:
  sessions: if-required
  oauth2:
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiSKHH02TInjoLiy+NlevFh7lLHlzMjl+DItzaBSh7ShrpwM2u0Lia05NYg2TACBnmVaouJ4xzM/kHT0V42w+FP1UEK3Grs/kQlNcjYdCi8+MrNL8cLHDlE/aStMncBy2iH0it9LYxyxAI+Ui6Xv3U1fXFhDz88Xia+JGb4YXVSr9+ducJiWE8iN8OCRpPJaWwww+ver5xAlICaftwd4w7turtfKNtgbcCGHETpa+bgcAhDxCBuvZA0HdRS6F9rP8TAhOtsenPsm0eKPsVp6ghOhI2l+8ykODONx+xUu9eREW48K6IvoW4VeoId24dzSXofoSpHbxG/uW3SWPBSVR6wIDAQAB
          -----END PUBLIC KEY-----
        


####### Temporary config - to be removed after testing ########

management:
  security:
    enabled: false
    
spring:
  cloud:
    config:
      enabled: false

####### Temporary config - END ################################  
  
---

spring:
  profiles: default
  
  h2:
    console:
      enabled: true