server:
  port: 8080
  
################# Logging configuration ###################

logging:
  level:
    org.springframework.security: debug
    com.netflix.discovery: off

################# Security Configuration ###################

auth:
  server:
    hostname: localhost

security:
  basic:
    enabled: false
  oauth2:
    client:
      access-token-uri: http://${auth.server.hostname}:9999/uaa/oauth/token
      user-authorization-uri: http://${auth.server.hostname}:9999/uaa/oauth/authorize
      client-id: webapp
      client-secret: websecret
    resource:
      jwt:
        key-value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiSKHH02TInjoLiy+NlevFh7lLHlzMjl+DItzaBSh7ShrpwM2u0Lia05NYg2TACBnmVaouJ4xzM/kHT0V42w+FP1UEK3Grs/kQlNcjYdCi8+MrNL8cLHDlE/aStMncBy2iH0it9LYxyxAI+Ui6Xv3U1fXFhDz88Xia+JGb4YXVSr9+ducJiWE8iN8OCRpPJaWwww+ver5xAlICaftwd4w7turtfKNtgbcCGHETpa+bgcAhDxCBuvZA0HdRS6F9rP8TAhOtsenPsm0eKPsVp6ghOhI2l+8ykODONx+xUu9eREW48K6IvoW4VeoId24dzSXofoSpHbxG/uW3SWPBSVR6wIDAQAB
          -----END PUBLIC KEY-----
    
management:
  security:
    enabled: false

################# Hystrix & Ribbon Timeouts ###############

# Disable Hystrix timeout globally (for all services)
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
          
ribbon:
  read-timeout: 30000
  connect-timeout: 30000

################# Zuul Routes ##########################

zuul:
  routes:
    resource-server:
      path: /resourceserver/**
      service-id: spring-oauth2-template-resource-server
    eureka-server:
      path: /eurekaserver/**
      service-id: spring-oauth2-template-eureka-server
    eureka-static:
      path: /eureka/**
      service-id: spring-oauth2-template-eureka-server
      strip-prefix: false
    ui-application:
      path: /**
      service-id: spring-oauth2-template-ui-application
      
            