server:
  port: 8080
  
################# Logging configuration ###################

logging:
  level:
    org.springframework.security: debug
    org.springframework.web: debug

################# Security Configuration ###################

auth:
  server:
    hostname: localhost

security:
  user:
    password: none
  oauth2:
    client:
      access-token-uri: http://${auth.server.hostname}:9191/uaa/oauth/token
      user-authorization-uri: http://${auth.server.hostname}:9191/uaa/oauth/authorize
      client-id: webapp
      client-secret: webappsecret
      grant-type: password
    resource:
      user-info-uri: http://${auth.server.hostname}:9191/uaa/user
    
management:
  security:
    enabled: false

################# Hystrix & Ribbon Timeouts ###############

# Disable Hystrix timeout globally (for all services)
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
          
ribbon:
  read-timeout: 30000
  connect-timeout: 30000

################# Zuul Routes ##########################

zuul:
  routes:
    auth-server:
      path: /authserver/**
      service-id: spring-oauth2-template-auth-server
    eureka-dashboard:
      path: /eurekaui/**
      service-id: spring-oauth2-template-eureka-server
      strip-prefix: false
    eureka-static:
      path: /eureka/**
      service-id: spring-oauth2-template-eureka-server
      strip-prefix: false
    config-server:
      path: /configserver/**
      service-id: spring-oauth2-template-config-server
    resource-server:
      path: /resourceserver/**
      service-id: spring-oauth2-template-resource-server
      