version: '2'
services:
  
  config-server:
    image: config-server
    ports:
      - "8888:8888"
    links:
      - eureka-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"