version: '2'
services:

  config-server:
    image: config-server
    ports:
      - "8888:8888"
    links:
      - eureka-server
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  auth-server:
    image: auth-server
    ports:
      - "9999:9999"
    links:
      - config-server
      - eureka-server
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  api-gateway:
      image: api-gateway
      ports:
          - "8080:8080"
      links:
        - config-server
        - eureka-server
        - auth-server
      environment:
        CONFIG_SERVER_URL: http://config-server:8888
        EUREKA_SERVER_URL: http://eureka-server:8761/eureka
        AUTH_SERVER_HOSTNAME: ${EXTERNAL_IP}

  resource-server:
      image: resource-server
      ports:
        - "9000:9000"
      links:
        - config-server
        - eureka-server
      environment:
        CONFIG_SERVER_URL: http://config-server:8888
        EUREKA_SERVER_URL: http://eureka-server:8761/eureka

  ui-application:
      image: ui-application
      ports:
        - "9001:9001"
      links:
        - config-server
        - eureka-server
      environment:
        CONFIG_SERVER_URL: http://config-server:8888
        EUREKA_SERVER_URL: http://eureka-server:8761/eureka
