version: '3'
services:
  
  config-server:
    image: config-server
    ports:
      - "8888:8888"
    networks:
      - service

  eureka-server:
    image: eureka-server
    ports:
      - "8761:8761"
    networks:
      - service

networks:
  service: