server:
  port: 9000
  
logging:
  level:
    com.netflix.discovery: off

auth:
  server:
    hostname: localhost

security:
  oauth2:
    resource:
      jwt:
        key-uri: http://localhost:9999/uaa/oauth/token_key
           


---

spring:
  profiles: default
  
security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
