server:
  port: 9000
  
logging:
  level:
    com.netflix.discovery: off

auth:
  server:
    hostname: localhost

security:
  oauth2:
    resource:
      user-info-uri: http://${auth.server.hostname}:9999/uaa/user


---

spring:
  profiles: default
  
security:
  basic:
    enabled: false
    
management:
  security:
    enabled: false
    
