server:
  port: 8761
  
logging:
  level:
    com.netflix.discovery: off

eureka:
  dashboard:
    path: /eurekaui
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      
---

spring:
  profiles: default

management:
  security:
    enabled: false