server:
  port: 8761
  
logging:
  level:
    com.netflix.discovery: off

eureka:
  dashboard:
    path: /eurekaui
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
      
---

spring:
  profiles: default

management:
  security:
    enabled: false