server:
  port: 8888

logging:
  level:
    com.netflix.discovery: off

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    healthcheck:
      enabled: true

---
spring:
  profiles: default
  
management:
  security:
    enabled: false